server:
  port: 8089
spring:
  application:
    name: Channel
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root1234
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate: dialect:org.hibernate.dialect.PostgreSQLDialkect
      format-sql: true